### ISSUE TITLE
Difference between scriptLoaded and global initialization

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-js#174]
Openhab-JS can execute code, whenever script is loaded using the scriptLoaded() function.  Intialization can be done also as normal code.  Compare:
```javascript
let x = 5
```
and
```javascript
let x
function scriptLoaded() {
  x = 5
}
```
in both cases `x` will be initialized to 5.

Please describe the use case for `scriptLoaded()`, which is not covered by normal initilization in JavaScript files.

**Comment by jpg0** [comment]
Is `scriptLoaded` still supported? I believe that I removed it (as well as `scriptUnloaded`) because it's non-standard JS and, as you say, appears to have no difference to just inline code. @digitaldan did you add this back in?

**Comment by dilyanpalauzov** [comment]
`scriptLoaded` is present at https://openhab.github.io/openhab-js/ and at https://github.com/openhab/openhab-js#initialization-hook-scriptloaded .  As far as I remember the purpose of `scriptUnloaded` was to cancel Java-Timers, otherwise they get leaked. Is this the right way to avoid timers leaking:
```javascript
let timer = actions.ScriptExecution.createTimer(time.ZonedDateTime.now().plusSeconds(10), () => { 
    …
    timer = null;
})

function scriptUnloaded() {
    timer?.cancel()
}
```
I am using OpenHAB 3.3.

**Comment by jpg0** [comment]
To hook into unloading, there is a lifecycle tracker: `lifecycleTracker.addDisposeHook(() => callSomething())`.

This was specifically designed to replace the `scriptUnloaded` functionality. But possibly this was retained too? Either way it looks like the docs need updating.

**Comment by dilyanpalauzov** [comment]
In openHAB 3.3 `scriptLoaded()` is executed, once the script is loaded, after the rules from the javascript file are loaded and the system logs “Adding rule:”.

**Comment by Dopeyr** [comment]
Wondering if this is UI rules vs filesystem rules: https://github.com/openhab/openhab-core/issues/2173

Maybe `scriptUnloaded()` only works with Filesystem rules?

**Comment by dilyanpalauzov** [comment]
> Maybe scriptUnloaded() only works with Filesystem rules?

For me it is still unclear whether the purpose of `scriptUnloaded()` is to reset Java-TImers, both in UI-rules and in filesystem rules.

**Comment by florian-h05** [comment]
> Is scriptLoaded still supported? I believe that I removed it (as well as scriptUnloaded) because it's non-standard JS 

`scriptLoaded` and `scriptUnloaded` are not provided by the addon, they are from core:

- https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java#L193
- https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java#L214

> `scriptLoaded` appears to have no difference to just inline code.

There is some difference: scriptLoaded is called after the script has been evaluated by the script engine, so scriptLoaded is executed after all the other code ran, regardless of where scriptLoaded is set up.
But I am wondering what the use case could be here.

> To hook into unloading, there is a lifecycle tracker: lifecycleTracker.addDisposeHook(() => callSomething()).

I wasn‘t aware of the lifecylceTracker (https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/LifecycleScriptExtensionProvider.java), but you are right that scriptUnloaded is also retained in the docs.

We can‘t remove scriptLoaded and scriptUnloaded because they are from core, but we could remove them from the docs. The question is: Should we remove them from the docs?
On one hand, they provide a really easy way to set up a initialization and deinitialization hook, but on the other hand they are some type of „magic“ that is added to JS.

**Comment by florian-h05** [comment]
I‘v also checked which of the hooks works where:

- `scriptLoaded`: seems to work for file-based scripts only
- `scriptUnloaded`: seems to work for both UI and file-based
- `lifecycleTracker` dispose hook: seems to work for both

**Comment by florian-h05** [comment]
> For me it is still unclear whether the purpose of scriptUnloaded() is to reset Java-TImers, both in UI-rules and in filesystem rules.

This is the most common use case for dispose/unload hooks I can think of. If you create timers using `createTimer`, you should do some sort of management, otherwise you can end up with unmanageable timers running until the next openHAB restart. If you use `setTimout` or `setInterval` for creating a timer, the timers are automatically cancelled when the script is unloaded.

**Comment by florian-h05** [comment]
I would remove `scriptLoaded` and `scriptUnloaded` from the docs (we cannot avoid that they are used, as they are from core) and instead of them document the lifecycleTracker.

@jpg0 Do you agree?

**Comment by jpg0** [comment]
> I would remove `scriptLoaded` and `scriptUnloaded` from the docs (we cannot avoid that they are used, as they are from core) and instead of them document the lifecycleTracker.
> 
> @jpg0 Do you agree?

Yes, sounds good to me
