### ISSUE TITLE
Feature request: Updating an existing JSRule()

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-js#40]
Is there any way to update an existing JSRule() or to replace it with a new rule?
This would be great to update Triggers, e.g. update a cron trigger.

I would use it in one manager rule to update the triggers of a child rule or I would also be happy with just removing the child rule and then adding a new child rule.

**Comment by jpg0** [comment]
@digitaldan this request relates to what I was saying about the current behaviour that _defining a rule = inserting a rule_.

@florian-h05 this is currently possible, however you need to explicitly get hold of the RuleManager, then update the rule via it's Java APIs. This isn't a great situation, and I believe that there should be a better way.

**Comment by florian-h05** [comment]
> @florian-h05 this is currently possible, however you need to explicitly get hold of the RuleManager, then update the rule via it's Java APIs.

Okay, that's complicated. 
Is this something that might be added to the library?

**Comment by jpg0** [comment]
First you need to get the rule registry. You can do this by calling `osgi.getService("org.openhab.core.automation.RuleRegistry")`.

Once you have one of these, you can call it to remove your own rule, then add a new one. The class is here: https://github.com/openhab/openhab-core/blob/79edf2b9e643ad802c31b2e5f54edb93534277fd/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/RuleRegistry.java

Ideally you would "update" the existing rule rather than replace it with a new one, but that will be difficult with the existing JS API as it's not possible to create a rule without inserting it too.

**Comment by florian-h05** [comment]
> First you need to get the rule registry. You can do this by calling `osgi.getService("org.openhab.core.automation.RuleRegistry")`.

Thank you very much, at the moment it seems that it works when I use `const { ruleRegistry } = require('@runtime/RuleSupport');` but it does not work using `const ruleRegistry = osgi.getService("org.openhab.core.automation.RuleRegistry")`.

**Comment by florian-h05** [comment]
> This isn't a great situation, and I believe that there should be a better way.

I am going to open a PR to support this directly with openhab-js.
