### ISSUE TITLE
getStateAs()

### ISSUE THREAD

**Issue by egoist6** [openhab/openhab-js#49]
Feature request to add `getStateAs()` to item class

**Comment by digitaldan** [comment]
We could expose this for sure on the item, what i'm not sure yet how to do is expose the possible state `Type`s  to pass into it, which include the following:
`DateTimeType, DecimalType, HSBType, OnOffType, OpenClosedType, PercentType, PlayPauseType, PointType, QuantityType, RawType, RewindFastforwardType, StringListType, StringType, UnDefType, UpDownType`

These are probably exposed via the `@Runtime` namespace, just not sure how to organize them in our library.

**Comment by jpg0** [comment]
My experience in dealing with these native types in JS was not great; I found many incompatibilities which is why I either converted to a raw JS type, or just a string.

I'm also not exactly sure what the use-cases for `getStateAs()` are?

**Comment by egoist6** [comment]
I am not by far the onewho could answer that question to its full scope.
I have raised this ticket due to a request of rlkoshak [here.](https://community.openhab.org/t/converting-dsl-rule-to-graaljs-script/130639)
The use case I am using it for is to get an OFF or ON state of items no matter if they are of type dimmer or on/off. This way it is possible to get all items where lights are either on or havea dimming state > 0.

**Comment by jpg0** [comment]
Note that `State` already has `as(..)`, so we don't really need `getStateAs(..)` as using `state.as(..)` should give you the same result.

**Comment by egoist6** [comment]
That's what I tried but it did not work. Here is the code:
`var OnOffType = Java.type("org.openhab.core.library.types.OnOffType");
items.getItem("gLampen").members
      .filter(i => i.state.as(OnOffType) == OnOffType.ON)
    .forEach( i => i.sendCommand("OFF"));`
I get the following error: `TypeError: i.state.as is not a function`
As you already stated, rawItem works:
`    .filter(i => i.rawItem.getStateAs(OnOffType) == OnOffType.ON)`

**Comment by digitaldan** [comment]
i think he meant `i.rawState.as(OnOffType)`

**Comment by digitaldan** [comment]
If we want to implement this, i think we will need to.....

A)  for the input we will need to export `@runtime` to a variable by default as we will need the openHAB specific types to pass into a getStateAs function on the JS item class (maybe support the enum string name as well) .   So for example 

```javascript
items.getItem("Foo").getStateAs(runtime.OnOffType)
``` 
or 
```javascript
items.getItem("Foo").getStateAs("OnOffType")
``` 

B) The output i think can be classified into either a ENUM type (like ON, OFF, UP, DOWN, etc....) which can be returned as a String, a Decimal  type which can be returned as a Number, or null (if null) .    The goal is to avoid returning non native JS types. 

```javascript
items.getItem("Foo").getStateAs(runtime.OnOffType) // returns the string "ON"
``` 

```javascript
items.getItem("Foo").getStateAs(runtime.PercentType) // returns the number 50
``` 

Thoughts?

**Comment by jpg0** [comment]
For A), I'd suggest creating an object called `type` (or `types`) with the types on it, so that you can use `type.OnOffType`.

For B), if we are planning to automatically coerce to JS types, then I think that we should take a deeper look at the relationship between existing openHAB and JS types, and how this is used. How many conversions do we need, and if the number is small can we do it in a more simple way? It seems like the primary use-cases are to 'downcast' by removing a dimension: e.g. from Number (scalar) to Boolean (PercentType to OnOffType) or a vector to a scalar (HSBType to PercentType). Is this the case? I also wonder if for your example we should really mix JS and openHAB types (in the parameter)? Seems weird to request an OnOffType and get a string. Are there multiple downcasts possible? For example can I request a PercentType as either an OnOffType or an OpenClosedType? Or can it only be downcast to a single enum type?

Also I personally I prefer `.state.as(..)` over `.getStateAs(..)` as the former pertains to the state object which afaics should be entirely independent to the item that it is for. Using `getStateAs(..)` couples state representations to the item object which seems like bad practice to me (for example we don't have `toString(format)` methods on objects either, the formatting pertains to the string, not the object).

**Comment by egoist6** [comment]
> i think he meant `i.rawState.as(OnOffType)` ?

sorry for not being clear:

- feature request: `i.Item.getStateAs(OnOffType) == ON`
- what is working today: `i.rawItem.getStateAs(OnOffType) == OnOffType.ON`
- jpg0 noted, 

> that State already has as(..)

My response was that `i.state.as(OnOffType)` leads to an error.

May I ask you s.th. different (and I certainly will open a new ticket if required). Are you aware of the memory leak issue which arises when you run too many JS scripts which have syntax faults included?

**Comment by jpg0** [comment]
> My response was that i.state.as(OnOffType) leads to an error.

This I regard as the real bug. Whilst `rawItem` works, it's really an escape hatch to allow direct access to the Java object for cases like this temporarily until they are properly supported.

I am aware of some threads about memory leaks, but haven't really looked at any of it.

**Comment by rkoshak** [comment]
@egoist6 I want to be clear I wanted the issue opened to have this conversation, not just to implement getStateAs() because I too think that the issue is deeper than just this one function. As hard as we try, we must come up with a consistent way to handle OH types in rules. 

> I'm also not exactly sure what the use-cases for getStateAs() are?

@jpg0 for one example, let's say you have a Group that is a mix of Switches, Dimmers, and Color Items and you want a list of all the members that are currently ON. With `getStateAs(OnOffType)` one can identify those Items regardless of the types of the Items and therefore the types of the states. 

> The goal is to avoid returning non native JS types.

I fear whether that will be possible with QuantityTypes which is always going to be a thorn in our sides when it comes to trying to keep everything as JS.

> For A), I'd suggest creating an object called type (or types) with the types on it, so that you can use type.OnOffType.

That was my first thought this morning as I was refreshing my memory on this issue. `getStateAs()` is merely one place where, despite our best efforts to normalize to JS, we will need to access the State types. So I would urge the consideration of A no matter what we decide to do about `as` or `getStateAs`. I personally prefer `types` to importing all of `runtime` if it's not needed.

> It seems like the primary use-cases are to 'downcast' by removing a dimension: e.g. from Number (scalar) to Boolean (PercentType to OnOffType) or a vector to a scalar (HSBType to PercentType). Is this the case?

Everywhere except QuantityTypes. And with more and more bindings using QuantityTypes I don't think we can just downcast like that in every case. There is also DateTimeType which I'm currently having problems with (I plan on opening a separate issue but the tl;dr is that openhab-js requires joda-js ZonedDateTimes but DateTimeType returns a Java ZonedDateTime which doesn't seem to be accepted, to schedule a Timer for example, and I've yet to find a way to create a joda-js ZonedDateTime from the Java ZonedDateTime, parsing the ISO8601 string always fails, I think we need to include js-locale in addition to `time`).

> My response was that i.state.as(OnOffType) leads to an error.

Well, `i.state` returns a String so of course there is no `as` method. But `i.rawState.as(OnOffType)` should work. After all, the code in GenericItem that implements `getStateAs()` just does that, calls `as()` on the State. https://github.com/openhab/openhab-core/blob/79edf2b9e643ad802c31b2e5f54edb93534277fd/bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java#L100

I don't have a strong opinion either way when it comes to implementing `i.getStateAs()` verses `i.rawState.as` or `i.state.as()`. I'd mention that the Item and the states already are inextricably tied to each other both in the openHAB code and the openHAB docs. So it doesn't bother me to have `getStateAs()` on the Item. 

My biggest concern over all is that we come up with a way to address this and related issues in a way that is intuitive and consistent across all of the library. The worst thing we can do is end up with a situation where it works one way when getting the Item from `items` and another way when iterating over a Group's members (for example). As part of that we always need to remind ourselves "but what of QuantityTypes?", especially when looking to normalize.

**Comment by florian-h05** [comment]
Closing as this is inactive and the reason why it was opened was solved in https://community.openhab.org/t/converting-dsl-rule-to-graaljs-script/130639/6?u=florian-h05.
