### ISSUE TITLE
custom installation (npm i openhab) results in ton of error log entries

### ISSUE THREAD

**Issue by lukicsl** [openhab/openhab-js#63]
It seems that something is not working with custom installation.
See community post:
[](https://community.openhab.org/t/custom-installation-of-openhab-js-problems/131411?)

**Comment by florian-h05** [comment]
Thank you for your posting, but there is no link to the community post.
I bet that you mean the posts here https://community.openhab.org/t/jsscripting-in-v3-2-loads-node-modules-on-startup/130357, where `node_modules` is loaded as script?

If you do: This problem is already known, there is an issue: https://github.com/openhab/openhab-addons/issues/11831. A PR to fix this bug is also open: https://github.com/openhab/openhab-addons/pull/11830

**Comment by lukicsl** [comment]
sorry: [https://community.openhab.org/t/custom-installation-of-openhab-js-problems/131411?u=lukics](https://community.openhab.org/t/custom-installation-of-openhab-js-problems/131411?u=lukics)

**Comment by florian-h05** [comment]
I answered to your post in the community forum.

**Comment by lukicsl** [comment]
@florian-h05 so to understand it right: the error message at custom installing and at code changes can be ignored for the moment. Things should work despite these error messages as expected?

**Comment by florian-h05** [comment]
As far as my experience goes, yes.
