### ISSUE TITLE
add runRule function to rules namespace

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-js#77]
Recent questions on the forum indicate there is a strong demand to create rules that call other rules. This is not directly supported by the library. Before I submit a PR I want to make sure this seems like something appropriate for openhab-js.

To me it seems like an obvious addition but will keep it in my own library if that isn't a direction we want to go. The code it pretty simple and it supports running a rule by UID or it will go and search for the rule by name. But I don't know if the search by name part will work in files for rules outside the one file, similar to the limitation with removeRule and findRule. I need to test that.

For reference:

```javascript
const runRule = (nameOrUid, argsDict, cond = false) => {
  // If it's not a UID, try to find it by name
  if(!RuleManager.getStatusInfo(nameOrUid)) {
    const rule = utils.javaSetToJsArray(ruleRegistry.getAll())
                      .find(rule => rule.getName(nameOrUid));
    nameOrUid = (rule) ? rule.getUID() : null;
  }

  // run the rule
  if(nameOrUid) {
    RuleManager.runNow(nameOrUid, cond, argsDict);
    return true;
  }
  else {
    return false;
  }
}
```

**Comment by digitaldan** [comment]
Sounds reasonable, question, can the rule manager run a disabled rule, so should that be checked first?  Also would it be better to throw an error if the rule can not be found or is disabled ?

**Comment by Confectrician** [comment]
Since we have the ability to define fixed and stable rule uids in ui and files, wouldn't it be good to run Rules only from those known id's instead of trying to guess something?

From my view the needed effort for finding the correct uid could be tolerated for a stable function.

> Also would it be better to throw an error if the rule can not be found or is disabled ?

To make it a bit more complicated (😜) we could also think about alowwing to run disabled rules via an additional parameter, set to `false` in default.

**Comment by rkoshak** [comment]
If the rule is disabled the RuleEngine will log out an error.

    2022-01-19 13:52:53.142 [ERROR] [e.automation.internal.RuleEngineImpl] - Failed to execute rule ‘tocall' with status 'UNINITIALIZED'

That's why I opted for a true/false return value. It's a little more informative than what OH itself does without being as disruptive as throwing an error. But I can absolutely check that the rule exists first and I'm fine with throwing an error in cases where it's disabled or can not be found. 

It's not clear to me what RuleManager does if you try to ask it to run a rule that doesn't exist. I'll have to mock up a quick test...

It also just logs a warning, this time

   2022-01-19 14:03:32.093 [WARN ] [e.automation.internal.RuleEngineImpl] - Failed to execute rule 'doesnotexist': Invalid Rule UID

> Since we have the ability to define fixed and stable rule uids in ui and files, wouldn't it be good to run Rules only from those known id's instead of trying to guess something?

It is not required for the users to supply the UID. The UID is somewhat deemphasized in MainUI. And for file based rules, if the user does not supply a UID, a random one gets generated every time the rule is loaded. So I added the ability to work with either the rule name or the UID to help those users who are not aware of the implications of failing to set the UID. It's not a guess though. The name must exactly match and if there are more than one rule with that name the first one found will be run (which is ambiguous I agree and we could throw an exception in that case too perhaps).

It's no big deal to take it out if we think that's a problem though. I can get rid of the need to use the ruleRegistry and just have to mess with the RuleManager in that case.

> To make it a bit more complicated (😜) we could also think about alowwing to run disabled rules via an additional parameter, set to false in default.

That's controlled by core. We can't change the behavior here. 

While I'm at it, should I add an enable and disable function? Or maybe we can just export the RuleManager as part of the Rules namespace which actually implements it. 

The new rule would look something like:

```
const runRule = (uid, argsDict, cond = false) => {
  if(!RuleManager.getStatusInfo(uid)) {
    throw 'There is no rule with UID ' + uid;
  }

  if(!RuleManager.isEnabled()) {
    throw 'Rule ' + uid + ' is not enabled';
  }

  RuleManager.runNow(nameOrUid, cond, argsDict);
}

const isEnabled = (uid) => {
  return RuleManager.isEnabled(uid);
}

const setEnabled = (uid, isEnabled) => {
  RuleManager.setEnabeled(uid, isEnabled);
}
```

As you can see, the enable/disable is just a passthrough to the RuleManager. We could check and throw an exception there too if the rule doesn't exist.

I'll start on a PR.

**Comment by digitaldan** [comment]
By the way i'm ok if we don't want to error if a rule is disabled or not, since the core seems to deal with that and log a message, this seems fine to ignore.  For not being found, that does seem like a condition that warrants an error.

**Comment by jpg0** [comment]
I have a question about the future guidance that we want to give script writers regarding reuse of functionality.

It seems that there are two possible use-cases here:

- Rule 'chaining' - one rule should be run as a result of some change in another rule
- Logic reuse - some functionality is already built into an existing rule and a user wants to reuse it

I am curious as I have written quite a lot of rules, which many of both of these two requirements, but have never had one rule trigger another. For the former case I have preferred to use standard triggers as the mechanism to chain rules (e.g. if an item changes then trigger the rule, rather than trigger it directly, as it should really depend on the state change). For the latter case I have used modules to share functionality.

I am assuming that the primary use-case for this feature is the latter one, because the former can already be achieved via triggers in the UI, yet the UI does not support adding module/library code.

Whilst I am not against encouraging users to create rules as a unit of reuse (essentially a subroutine that can be called from elsewhere), I do expect it to create a division in how scripted systems are constructed between UI and file based systems. For example it's not really possible to share code written as callable rules, and the parameter sets and style of this coding is quite distinct from being written as a function in a module.

I just wanted to highlight that explicit support for reuse-via-rules does make this implicit decision that we are supporting two, incompatible mechanisms of logic reuse. I guess that the alternative would be explicit support for library authorship in the UI (somewhat akin to 'widgets' in the UI builder pages), but that's a much more involved change.

**Comment by rkoshak** [comment]
Here is my primary use case for this. 

I've a number of rule templates published to the marketplace. The easiest example is probably https://community.openhab.org/t/alarm-clock-rule/127194. Rules generated from this template will schedule a Timer based on a DateTime Item (probably something that should be implemented by core anyway but it's not so I wrote a rule template). But I can't predict what the end user will want to do when that Timer goes off. They could want to do almost anything.

So the template has the user write a separate rule that gets called by the rule generated by the template. All the end user has to worry about is the "what", not the "how". They just have to code what to do when the DateTime is reached, not mess with how to make that code run at the right time.

I've also got a Threshold Alert rule template that checks the members of a Group to see if any Items meet a criteria. I can't predict what the users may want to do when such Items are found so I call a separate rule they write and pass a list of the Items that match their criteria.

I've also a Thing Status Alert rule template that checks all the Things to see if it matches a criteria. This will call a rule created by the user with the list of Things.

When it comes to rule templates, chaining rules together like this makes certain types of rule templates much more powerful. And unlike a module, when one rule calls another they don't have to be the same language. So a user can install my template which is currently Nashorn ECMAScript 5.1 (soon to be ported to 11) and that call their Blockly rule. 

So in this case it flips the code reuse on its head. It's the rule template that's making the call but it's the rule template that's the unit of reuse. The called script is where the custom code goes. 

> For the former case I have preferred to use standard triggers as the mechanism to chain rules

You are limited in what sorts of data you can pass to the other rule in this way. When calling a rule from another rule you can pass pretty much anything including Timers and stuff like that.

> For example it's not really possible to share code written as callable rules
The Marketplace Rule Templates are the way to share such code.

> I just wanted to highlight that explicit support for reuse-via-rules does make this implicit decision that we are supporting two, incompatible mechanisms of logic reuse.

This presupposes that the two are equivalent. There are some use cases that can only be supported by rule chaining. There are other use cases that can only be supported via a module. There is some overlap in the sorts of things they make possible but that overlap is not 100%. 

Having a way to write modules in MainUI would be awesome! But I'd still want to be able to call a rule from another rule. It's not just about reuse.

**Comment by rkoshak** [comment]
> By the way i'm ok if we don't want to error if a rule is disabled or not, since the core seems to deal with that and log a message, this seems fine to ignore. For not being found, that does seem like a condition that warrants an error.

I missed this reply earlier. 

The core deals with this the same way as when the rule is disabled, with an ERROR level message in the logs. So I would argue to throw an error in both cases or neither case. If we want to throw the error we need to implement methods rather than just exposing RuleManager. We can include the same information in the error as is in the logs from openHAB core.

**Comment by jpg0** [comment]
> So in this case it flips the code reuse on its head. It's the rule template that's making the call but it's the rule template that's the unit of reuse. The called script is where the custom code goes.

Right - the rule chaining use-case is different, I assumed the wrong use-case. However if I look at how most of the rule-chaining use-case works in openHAB, it's via channels. So typically your rules would put events into a channel, then users could configure their rules to trigger based on that channel. This seems both more flexible (triggers can do more than just a direct call, they can delay, debounce, coalesce events etc, and you can register many triggers, even dynamically if you like), and also more aligned with how everything else in openHAB works (for example if you were to write a 'Threshold' *add-on* it would most likely publish it's output on a channel).

As I mentioned, I'm not specifically against adding this function, but IMO it's not the way that we should be encouraging the use-case.

**Comment by rkoshak** [comment]
So are you arguing that any use case that has one rule call another should be implemented as an add-on and should not be implemented as a rule template? If that's the case rule templates would be *way* less useful and interesting as a concept over all. 

> for example if you were to write a 'Threshold' add-on it would most likely publish it's output on a channel)

I couldn't implement such an add-on because bindings, by policy and design, do not have access to all the Items (that's why the MQTT EventBus has to be implemented as rules instead of as part of the MQTT Binding). There would be no way for such an add-on to see the Items in order to find which ones exceed the threshold. I don't know if the same is true for Things but it makes sense that any given binding wouldn't have access to any but it's own Things. 

So unless there's a way to create Channels inside a rule and have it visible to the end users to select when triggering a rule, what you describe isn't possible. And even if there were a way to create such a Channel, the amount and types of data that can be passed as part of that Channel Event is limited to a single String which further limits it. Furthermore, many of the features you describe like delaying, debouncing, transforming, etc are handled by Profiles which only exist on the link between a Channel and an Item, not for event Channels.

Given my knowledge of these things, I don't see how what you describe is possible. I can't create a Channel form a rule and a binding cannot access the Items.

**Comment by jpg0** [comment]
> So are you arguing that any use case that has one rule call another should be implemented as an add-on and should not be implemented as a rule template?

No, I'm arguing that the rule should post an event to a channel when appropriate, rather than call another rule.

For example, let's take threshold functionality. The way I could imagine this working is that a rule template would allow you to create a rule that takes the parameters:

- The item to monitor
- The threshold value
- The channel to notify when the threshold is reached

The user would configure the rule as appropriate, then configure a second rule to listen to the channel being posted to. I understand that only a string is possible to use as a parameter, but that doesn't stop things like MQTT using it for arbitrary payloads, in the form of JSON. I think it's then possible to apply processing at the trigger point for the rule (that listens for the events) to get extra functionality? (For example I have a 'QuiesedItemStateChangeTrigger' which only fires when items' state changes and then settles.)

As for creation of a *new* channel - I believe that this is absolutely possible via the openHAB API and hence a script (although we could certainly make it simpler in the JS API).

**Comment by rkoshak** [comment]
I'd love to know how. It would be fun to see how it's done. But as far as I've been able to determine looking at the code and the APIs, Channels can only exist as part of a Thing. There is no way to define one outside the context of a Thing. They certainly are not stored in the JSONDB outside the context of a Thing. There is no REST API endpoint to create a Channel independently from a Thing. The channel-types end point only has getters, not setters or updaters. There is no ChannelRegistry where we could submit such a naked Channel to exist on it's own.

By all appearances, OH is designed such that Channels are only relevant to Things.  

Yet, even as far back as OH 2's Experimental Rules Engine there has been support for rules that call other rules with UI defined rules. It's not a new action type. MainUI has as one of its four categories "other rules" where, in addition to enable and disable is "run these rule(s)". It's already there, front and center in the UI. People are already using it (including @Confectrician above). 

But, I don't know everything. Despite appearances it perhaps it is possible to create a naked Channel. If that's the case I'd love to see how and experiment with it. My argument isn't that using Channels is a bad idea, I just don't see how it's possible at all.

> but that doesn't stop things like MQTT using it for arbitrary payloads, in the form of JSON

True, but then the called rule is forced to parse that event to get the information back out of it. And to a large extent that would be a misuse of the event Channel. Event channels are intended to represent momentary and stateless events. If you are parsing out a bunch of JSON that probably means you are dealing with state, not a momentary event. Though there are always exceptions. 

>  I think it's then possible to apply processing at the trigger point for the rule (that listens for the events) to get extra functionality? (For example I have a 'QuiesedItemStateChangeTrigger' which only fires when items' state changes and then settles.)

Only if new features are added to the core. There is no such feature I'm aware of today. Today, the only processing that can be done before the rule triggers (outside of the binding itself) is via Profiles, which only exist on the links between STATE Channels and Items. You can't apply a Profile to a TRIGGER type Channel. Adding that ability would be adding a whole new capability to OH core.

**Comment by jpg0** [comment]
> Channels can only exist as part of a Thing

I have indeed only created channels as part of a Thing - which can be created from scripts. I agree that I don't think it's possible to have a channel without a Thing (although I believe that you can put anything on the openHAB event bus internally, so it may be possible). In the Threshold example there could be a 'ThresholdMonitor' Thing created from where the channels originate. This is very similar to how the Astro binding works.

> that would be a misuse of the event Channel

That is possibly the case, depending on what is being put into the channel. I have an example of using a custom channel to broadcast any detected incoming 433Mhz Rf signals, where the details of the signal is in the event payload as JSON. One such signal is a wireless doorbell, where I have multiple rules subscribing to the channels to act upon the doorbell being pressed. I'm not sure if this is the correct use of a channel, but it works well for me (and appears more flexible than calling the subscribers directly).

> Only if new features are added to the core

I see what you are saying - that we already have this divergence within openHAB such that the only thing that you can do with trigger channels is listen for a specific string (payload). That is certainly unfortunate. The mechanism I have been using (due to the low traffic on these channels) is to listen for all events, then only process the rule code if it's an event that I'm interested in. It would be pretty trivial to add some basic filtering code to a trigger channel to (for example) validate a JSON field or something.

Ultimately, the way to really think about how this *should* be constructed is by what dependencies should lie in what direction. In the case that I originally mentioned (library/module), then the dependency is explicitly that some logic depends on something else happening, so it should be explicitly calling into it (and the lib should not care about callers). In the case that we are talking about now with channels, typically the dependency exists the other way around - some action should occur if something reaches a threshold (and the threshold logic shouldn't care about these actions). This, I would imagine, is the ideal way around. If we are interested in making this possible, I'm happy to try to add things like payload filtering to trigger channel listeners. This does make me wonder if a goal for scripting should be that it's possible to write a binding in it - so that for users they get the same experience when installing scripting modules like your examples versus bindings.

**Comment by rkoshak** [comment]
> In the Threshold example there could be a 'ThresholdMonitor' Thing created from where the channels originate. This is very similar to how the Astro binding works.

Would that show up under Things? What would manage its ONLINE/OFFLINE status? I've never done it from a rule but when I've had Things created by a binding that I've removed, that Thing remains in an OFFLINE state. Perhaps the rule can manage the state of the Thing? But then we've come a really long way from a simple function call to a whole host of creation and management activities required by the rule author.

I don't really have an objection with the possibility of creating and using Channels from a rule. But only if those Things:

- act and behave in a consistent manner with other Things (in this case probably as read only Things like those defined in files)
- do not present errors to the user (e.g. appear OFFLINE because there is no binding to tell OH it's ONLINE)
- do not impose a significant amount of extra work on the rule template writer or the "called rule" writer.

Failing that I don't see how encouraging the use of Channels is better for the end users. It's more work for both the caller and the called.

> where I have multiple rules subscribing to the channels to act upon the doorbell being pressed. I'm not sure if this is the correct use of a channel, but it works well for me (and appears more flexible than calling the subscribers directly).

That is a good use of the MQTT event channel. Pressing the doorbell is a momentary action, not something that carries state. So it makes sense to use the Event Channel for that. It would be a misuse if, for example, the Channel is used to parse out the current state of a bunch of lights (for example), updating the Items as required because it's "easier" than creating separate MQTT Channels. The distinction is the nature of the message. Is it stateless or stateful? If you update an Item as a result of the message, it's probably better to use a State Channel. Though, as always there will be exceptions.

> It would be pretty trivial to add some basic filtering code to a trigger channel to (for example) validate a JSON field or something.

That sounds like a Condition, though that's part of the rule instead of the trigger so maybe it's too late in the chain?

> This does make me wonder if a goal for scripting should be that it's possible to write a binding in it - so that for users they get the same experience when installing scripting modules like your examples versus bindings.

I know some have gone this way but I've always been uncomfortable with the concept. These bindings wouldn't appear in OH the same as other bindings. They won't be OSGi bundles, won't have the same sorts of life cycles, configuration options, etc. On-the-other-hand, it could increase the population of developers who can and are willing to write bindings. 

It feels a whole lot like Profiles though. By creating yet another way to do something, it only adds to the complexity instead of making things easier. I'm constantly having to inform people "I'm sorry, you can't do that with a Profile, you have to write a rule" and they get angry because intuitively what they want to do is not a lot different from what other Profiles do but there are hidden technical limitations that prevent Profiles from doing it.

**Comment by jpg0** [comment]
> Would that show up under Things? What would manage its ONLINE/OFFLINE status?

Yes. The way I have done it in script is that the script provides it's own definitions of things from memory, it does *not* use managed providers. This way if the script goes away, so does everything attached to it - it is not longer present at all, so does not end up in an OFFLINE state or anything. TBH I suspect that it would be better to change JSRule to create unmanaged rules too, but I never got around to doing that... W.r.t. your requirements for scripted Things, I completely agree with them all.

> That sounds like a Condition

Ok - great - so Conditions could be used with trigger channels? I have not used them as it was just as easy to put the code at the start of the rule, but if you are using the UI I understand the benefit.

I'm not fussed either way about supporting Bindings created by scripts, however I would say that they should absolutely behave (but not install/uninstall) the same way as native Java osgi bundles. TBH the way I have implemented them is pretty much the same - provide the right interfaces to osgi and it all happens - it doesn't matter if the interface comes from Java directly, or via Graal and JS, openHAB doesn't care, and it should all be presented to the user in exactly the same way.

**Comment by rkoshak** [comment]
I'm going to close this issue since the PR has been merged. It's probably best to open a new one to pursue the rule Channels Idea.
